# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[rust]
codegen-backends = ["llvm", "cranelift"]
deny-warnings = false

[build]
host = ["wasm32-wasi"]
target = ["x86_64-unknown-linux-gnu"]

[install]
prefix = "dist"
sysconfdir = "etc"

[target.'wasm32-wasi']
wasi-root = "wasi-sdk-20.0/share/wasi-sysroot"
linker = "wasi-sdk-20.0/bin/clang"

[target.'x86_64-unknown-linux-gnu']
cc = "gcc"
